In [1]:
people ={
    "first" : ['corey','jane', 'john'],
    "last" : ['ss','doe','doe'],
    "email" : ['cc@gmail.com','jane@gmail.com','john@gmail.com' ]
    
}

In [2]:
people['email']

['cc@gmail.com', 'jane@gmail.com', 'john@gmail.com']

In [3]:
import pandas as pd

In [4]:
df = pd.DataFrame(people) # creating data frame

In [5]:
df

   first last           email
0  corey   ss    cc@gmail.com
1   jane  doe  jane@gmail.com
2   john  doe  john@gmail.com

#access values in  data frame

In [6]:
df['email']  # df.email

0      cc@gmail.com
1    jane@gmail.com
2    john@gmail.com
Name: email, dtype: object

In [7]:
type(df['email'])

pandas.core.series.Series

In [8]:
# series is list of data -- 1 D array -- single column row of data
# data frame -- container for multiple series

In [9]:
df[['last','email']] # not a series as not single column

  last           email
0   ss    cc@gmail.com
1  doe  jane@gmail.com
2  doe  john@gmail.com

In [10]:
 df.columns

Index(['first', 'last', 'email'], dtype='object')

In [11]:
#  iloc - to get rows by index --> last value is inclusive


df.iloc[0]
df.iloc[[0,1]]  # to get list of rows
df.iloc[[0,1],2] # to get rows and colums

0      cc@gmail.com
1    jane@gmail.com
Name: email, dtype: object

In [12]:
#loc   - to get rows --> last value is inclusive
df.loc[0]

first           corey
last               ss
email    cc@gmail.com
Name: 0, dtype: object

In [13]:
df.loc[[1,2]]

  first last           email
1  jane  doe  jane@gmail.com
2  john  doe  john@gmail.com

In [14]:
df.loc[[0,1],['email','last']]

            email last
0    cc@gmail.com   ss
1  jane@gmail.com  doe

# Now go to Pandas Demo till 43

In [15]:
df['email']

0      cc@gmail.com
1    jane@gmail.com
2    john@gmail.com
Name: email, dtype: object

In [16]:
# set entity as  index for data frame  - email as index - at first col  -> only view no change in dataset 

df.set_index('email')

                first last
email
cc@gmail.com    corey   ss
jane@gmail.com   jane  doe
john@gmail.com   john  doe

In [17]:
df # no change below

   first last           email
0  corey   ss    cc@gmail.com
1   jane  doe  jane@gmail.com
2   john  doe  john@gmail.com

In [18]:
df.set_index('email',inplace=True)  # will change dataset

In [19]:
df  # dataset changed below

                first last
email
cc@gmail.com    corey   ss
jane@gmail.com   jane  doe
john@gmail.com   john  doe

In [20]:
df.index #get list of index and their values

Index(['cc@gmail.com', 'jane@gmail.com', 'john@gmail.com'], dtype='object', name='email')

In [21]:
df.loc['john@gmail.com']  # work bcz of email as index

first    john
last      doe
Name: john@gmail.com, dtype: object

In [22]:
df.loc['john@gmail.com', 'last']   #give last name for mentioned email

'doe'

In [23]:
# This drops the current index completely and replaces it with a fresh 0, 1, 2... index
df.reset_index(drop=True, inplace=True)
df

   first last
0  corey   ss
1   jane  doe
2   john  doe

## LEC 4

### Filter

In [24]:
df

   first last
0  corey   ss
1   jane  doe
2   john  doe

In [25]:
filt = (df['last'] == 'doe')

In [26]:
df

   first last
0  corey   ss
1   jane  doe
2   john  doe

In [27]:
df[filt]

  first last
1  jane  doe
2  john  doe

In [28]:
df.loc[filt]

  first last
1  jane  doe
2  john  doe

In [29]:
df = pd.DataFrame(people) # re-creating original data frame

In [30]:
df.loc[filt, 'email']

1    jane@gmail.com
2    john@gmail.com
Name: email, dtype: object

In [31]:
filt = (df['last'] == 'doe')  & (df['first'] == 'john')
df[filt]

  first last           email
2  john  doe  john@gmail.com

In [32]:
df.columns

Index(['first', 'last', 'email'], dtype='object')

In [33]:
df.columns = ['first_name', 'last_name', 'email']

In [34]:
df.columns

Index(['first_name', 'last_name', 'email'], dtype='object')

In [35]:
df.columns =[x.upper() for x in df.columns]  # convert col name to upper case
df

  FIRST_NAME LAST_NAME           EMAIL
0      corey        ss    cc@gmail.com
1       jane       doe  jane@gmail.com
2       john       doe  john@gmail.com

In [36]:
# replace 
df.columns = df.columns.str.replace('_',' ')
df

  FIRST NAME LAST NAME           EMAIL
0      corey        ss    cc@gmail.com
1       jane       doe  jane@gmail.com
2       john       doe  john@gmail.com

In [37]:
df.columns = ['first_name', 'last_name', 'email'] # reset to original

In [38]:
# rename specific col
df.rename(columns = {'first_name': 'first', 'last_name': 'last'}, inplace=True)
df

   first last           email
0  corey   ss    cc@gmail.com
1   jane  doe  jane@gmail.com
2   john  doe  john@gmail.com

In [39]:
#access rows

In [40]:
df.loc[2]

first              john
last                doe
email    john@gmail.com
Name: 2, dtype: object

In [41]:
# chnage value of a col
df.loc[2] = ['john','smith','johns@gmail.com']
df

   first   last            email
0  corey     ss     cc@gmail.com
1   jane    doe   jane@gmail.com
2   john  smith  johns@gmail.com

In [42]:
#chnage colm by passing colms  name
df.loc[2, ['last','email']] = ['doe','jodoe@gmail.com']
df

   first last            email
0  corey   ss     cc@gmail.com
1   jane  doe   jane@gmail.com
2   john  doe  jodoe@gmail.com

In [43]:
df.loc[2, 'last'] = 'smith'
df

   first   last            email
0  corey     ss     cc@gmail.com
1   jane    doe   jane@gmail.com
2   john  smith  jodoe@gmail.com

In [44]:
df.at[2,'last'] = 'simon'
df

   first   last            email
0  corey     ss     cc@gmail.com
1   jane    doe   jane@gmail.com
2   john  simon  jodoe@gmail.com

In [45]:
df

   first   last            email
0  corey     ss     cc@gmail.com
1   jane    doe   jane@gmail.com
2   john  simon  jodoe@gmail.com

In [46]:
filt = (df['email'] == 'jodoe@gmail.com')
df[filt]['last'] ='Smith' 
# will throw warning and wont make chnages - see below df line  - due to it's temp chnage and it won't 
# won't work as it's just view  but df.loc will work

C:\Users\SUSAJJIT\AppData\Local\Temp\ipykernel_3700\2508861174.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[filt]['last'] ='Smith'

In [47]:
df

   first   last            email
0  corey     ss     cc@gmail.com
1   jane    doe   jane@gmail.com
2   john  simon  jodoe@gmail.com

In [48]:
# will make changes to df
filt = (df['email'] == 'jodoe@gmail.com')
df.loc[filt,'last'] ='smith'

In [49]:
df

   first   last            email
0  corey     ss     cc@gmail.com
1   jane    doe   jane@gmail.com
2   john  smith  jodoe@gmail.com

In [50]:
 # show email in lower case
df['email'].str.lower()

0       cc@gmail.com
1     jane@gmail.com
2    jodoe@gmail.com
Name: email, dtype: object

## Modification methods in data frame
1. apply, 2.map, 3. apply map, 4. replace

### 1. Apply

In [51]:
df['email'].apply(len) #len of email

0    12
1    14
2    15
Name: email, dtype: int64

In [52]:
#update values - temp

def update_email(email):
    return email.upper()

In [53]:
df['email'].apply(update_email)

0       CC@GMAIL.COM
1     JANE@GMAIL.COM
2    JODOE@GMAIL.COM
Name: email, dtype: object

In [54]:
df['email'] = df['email'].apply(update_email) # permannet chnage as assigning

In [55]:
df

   first   last            email
0  corey     ss     CC@GMAIL.COM
1   jane    doe   JANE@GMAIL.COM
2   john  smith  JODOE@GMAIL.COM

In [56]:
# lambda func

df['email'] = df['email'].apply(lambda x: x.lower()) # permannet chnage as assigning

In [57]:
df

   first   last            email
0  corey     ss     cc@gmail.com
1   jane    doe   jane@gmail.com
2   john  smith  jodoe@gmail.com

In [58]:
df.apply(len)  # len of each colm = no of rows
len(df['email'])  # same as above

3

In [59]:
df.apply(len, axis='columns')  # no of colm in each row

0    3
1    3
2    3
dtype: int64

In [60]:
# min value in each col alphabetically  - it uses ASCII for comparing
df.apply(pd.Series.min) # series is more useful for numerical data

first           corey
last              doe
email    cc@gmail.com
dtype: object

In [61]:
df.apply(lambda x: x.min()) # series is more useful for numerical data

first           corey
last              doe
email    cc@gmail.com
dtype: object

In [62]:
# running apply on a series - apply a func to every value in the series
# running apply on a data frame -- apply a func to every series in data frame

## 2 applymap

In [63]:
# applymap - used to apply  a fun to all individual value in data frame
# len of all individual in all the rows and colmns

df.applymap(len)

   first  last  email
0      5     2     12
1      4     3     14
2      4     5     15

In [64]:
df.applymap(str.lower)

   first   last            email
0  corey     ss     cc@gmail.com
1   jane    doe   jane@gmail.com
2   john  smith  jodoe@gmail.com

## 3. map

In [65]:
# make chnages to a series  -- ; values which are not substituted/assigned below will give NaN

df['first'].map({'corey' : 'Chrish', 'jane': 'Mary'})

0    Chrish
1      Mary
2       NaN
Name: first, dtype: object

## 4. Replace

In [66]:
# keep John but change other -- will chnage what is susbtituted - others will reamin same
df['first'].replace({'corey' : 'Chrish', 'jane': 'Mary'})

0    Chrish
1      Mary
2      john
Name: first, dtype: object

In [67]:
df['first'].replace({'Steve' : 'steve'})

0    corey
1     jane
2     john
Name: first, dtype: object

# LEC 6

In [68]:
# add or remove colm

#combine first and last name and call it full_name
# can't use .(dot) to assign -- python will think - trying to assign an attribute on thr df
# object and not a colmn

df['full_name'] = df['first'] + ' ' + df['last'] # concatanation
df

   first   last            email   full_name
0  corey     ss     cc@gmail.com    corey ss
1   jane    doe   jane@gmail.com    jane doe
2   john  smith  jodoe@gmail.com  john smith

In [69]:
df.drop(columns ={'first','last'}, inplace = True)

In [70]:
df

             email   full_name
0     cc@gmail.com    corey ss
1   jane@gmail.com    jane doe
2  jodoe@gmail.com  john smith

In [71]:
# split full name in first and last

df['full_name'].str.split(' ')

0      [corey, ss]
1      [jane, doe]
2    [john, smith]
Name: full_name, dtype: object

In [72]:
df['full_name'].str.split(' ', expand = True) # to get splitted values in colms

       0      1
0  corey     ss
1   jane    doe
2   john  smith

In [73]:
# creating nre colms --  assigning splitted expanded values to new colms
df[['first', 'last']] = df['full_name'].str.split(' ', expand = True)

In [74]:
df

             email   full_name  first   last
0     cc@gmail.com    corey ss  corey     ss
1   jane@gmail.com    jane doe   jane    doe
2  jodoe@gmail.com  john smith   john  smith

In [75]:
# Add rows to df

# TypeError: Can only append a dict if ignore_index=True
# df.append({'first' : 'Tony'})  # throw above error - as it doesnt have index currently

df.append({'first' : 'Tony'}, ignore_index=True)

C:\Users\SUSAJJIT\AppData\Local\Temp\ipykernel_3700\2533046534.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df.append({'first' : 'Tony'}, ignore_index=True)

             email   full_name  first   last
0     cc@gmail.com    corey ss  corey     ss
1   jane@gmail.com    jane doe   jane    doe
2  jodoe@gmail.com  john smith   john  smith
3              NaN         NaN   Tony    NaN

In [76]:
people ={
    "first" : ['tony','Steve'],
    "last" : ['stark','Rogers'],
    "email" : ['Ironman@gmail.com','Cap@gmail.com']
    
}

df2 = pd.DataFrame(people)

In [77]:
df2

   first    last              email
0   tony   stark  Ironman@gmail.com
1  Steve  Rogers      Cap@gmail.com

In [78]:
# adding rows to data frame from other
# df.append(df2, ignore_index=True) # temp  - append - depricated
# df.append(df2, ignore_index=True) # temp 
pd.concat([df, df2], ignore_index=True)

               email   full_name  first    last
0       cc@gmail.com    corey ss  corey      ss
1     jane@gmail.com    jane doe   jane     doe
2    jodoe@gmail.com  john smith   john   smith
3  Ironman@gmail.com         NaN   tony   stark
4      Cap@gmail.com         NaN  Steve  Rogers

In [79]:
# df = df.append(df2, ignore_index=True) # permanent
df = pd.concat([df, df2], ignore_index=True)

In [80]:
# find the full_name with NaN  value and assign them with cooncat of first and last

df.loc[df['full_name'].isna(), 'full_name'] = df['first'] + ' ' + df['last']

In [81]:
df

               email     full_name  first    last
0       cc@gmail.com      corey ss  corey      ss
1     jane@gmail.com      jane doe   jane     doe
2    jodoe@gmail.com    john smith   john   smith
3  Ironman@gmail.com    tony stark   tony   stark
4      Cap@gmail.com  Steve Rogers  Steve  Rogers

In [82]:
# removing row

df.drop(index = 4)

               email   full_name  first   last
0       cc@gmail.com    corey ss  corey     ss
1     jane@gmail.com    jane doe   jane    doe
2    jodoe@gmail.com  john smith   john  smith
3  Ironman@gmail.com  tony stark   tony  stark

In [83]:
# drop row where last name = doe
# df.drop(index = df[df['last'] == 'doe'].index) # .index used to get index as row operations are performed on index
# below code is just more wrt above - same operarion
filt = df['last'] == 'NaN'
df.drop(index = df[filt].index)

               email     full_name  first    last
0       cc@gmail.com      corey ss  corey      ss
1     jane@gmail.com      jane doe   jane     doe
2    jodoe@gmail.com    john smith   john   smith
3  Ironman@gmail.com    tony stark   tony   stark
4      Cap@gmail.com  Steve Rogers  Steve  Rogers

In [84]:
# df = df.drop('Steve')   # to drop a row with index "Steve"

## Lec 7

### Sorting

In [85]:
df.sort_values(by='first')  # asc

               email     full_name  first    last
4      Cap@gmail.com  Steve Rogers  Steve  Rogers
0       cc@gmail.com      corey ss  corey      ss
1     jane@gmail.com      jane doe   jane     doe
2    jodoe@gmail.com    john smith   john   smith
3  Ironman@gmail.com    tony stark   tony   stark

In [86]:
df.sort_values(by='first', ascending = False)  # desc

               email     full_name  first    last
3  Ironman@gmail.com    tony stark   tony   stark
2    jodoe@gmail.com    john smith   john   smith
1     jane@gmail.com      jane doe   jane     doe
0       cc@gmail.com      corey ss  corey      ss
4      Cap@gmail.com  Steve Rogers  Steve  Rogers

In [87]:
#  sort by mutilple params  - if clash on first filter will sort by second and ....

df.sort_values(by = ['last', 'first'], ascending=False) # desc by both param

               email     full_name  first    last
3  Ironman@gmail.com    tony stark   tony   stark
0       cc@gmail.com      corey ss  corey      ss
2    jodoe@gmail.com    john smith   john   smith
1     jane@gmail.com      jane doe   jane     doe
4      Cap@gmail.com  Steve Rogers  Steve  Rogers

In [88]:
df.sort_values(by = ['last', 'first'], ascending=[False,True]) # desc - last , asc - first

               email     full_name  first    last
3  Ironman@gmail.com    tony stark   tony   stark
0       cc@gmail.com      corey ss  corey      ss
2    jodoe@gmail.com    john smith   john   smith
1     jane@gmail.com      jane doe   jane     doe
4      Cap@gmail.com  Steve Rogers  Steve  Rogers

In [89]:
df.sort_values(by = ['last', 'first'], ascending=[False,True], inplace=True)

In [90]:
# sort by index - to get in original format
df.sort_index()

               email     full_name  first    last
0       cc@gmail.com      corey ss  corey      ss
1     jane@gmail.com      jane doe   jane     doe
2    jodoe@gmail.com    john smith   john   smith
3  Ironman@gmail.com    tony stark   tony   stark
4      Cap@gmail.com  Steve Rogers  Steve  Rogers

In [91]:
# to sort a single col

df['last'].sort_values()

4    Rogers
1       doe
2     smith
0        ss
3     stark
Name: last, dtype: object

## Lec 8

## Lec 9

In [92]:

import pandas as pd

In [93]:
na_vals = ['NA', 'Missing']
df = pd.read_csv('results.csv', index_col='Respondent', na_values=na_vals) # na_values = nan
schema_df = pd.read_csv('schema.csv', index_col='Column')

In [94]:
# to display max no of rows and colms
pd.set_option('display.max_columns', 85)
pd.set_option('display.max_rows', 85)

In [95]:
df.head()

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [96]:
df['YearsCode'].head(10)

Respondent
1       4
2     NaN
3       3
4       3
5      16
6      13
7       6
8       8
9      12
10     12
Name: YearsCode, dtype: object

In [97]:
# df['YearsCode'].mean()  # error due to nan float
# TypeError: can only concatenate str (not "int") to str

# casting
# df['YearsCode'] = df['YearsCode'].astype(float) # some values were string 
# ValueError: could not convert string to float: 'Less than 1 year'

# get unique values of colm to see all data types and format them correctly

df['YearsCode'].unique()

array(['4', nan, '3', '16', '13', '6', '8', '12', '2', '5', '17', '10',
       '14', '35', '7', 'Less than 1 year', '30', '9', '26', '40', '19',
       '15', '20', '28', '25', '1', '22', '11', '33', '50', '41', '18',
       '34', '24', '23', '42', '27', '21', '36', '32', '39', '38', '31',
       '37', 'More than 50 years', '29', '44', '45', '48', '46', '43',
       '47', '49'], dtype=object)

In [98]:
# converting diff data type to num
df['YearsCode'].replace('Less than 1 year', 0, inplace=True)
df['YearsCode'].replace('More than 50 years', 51, inplace=True)

In [99]:
df['YearsCode'].unique()

array(['4', nan, '3', '16', '13', '6', '8', '12', '2', '5', '17', '10',
       '14', '35', '7', 0, '30', '9', '26', '40', '19', '15', '20', '28',
       '25', '1', '22', '11', '33', '50', '41', '18', '34', '24', '23',
       '42', '27', '21', '36', '32', '39', '38', '31', '37', 51, '29',
       '44', '45', '48', '46', '43', '47', '49'], dtype=object)

In [100]:
df['YearsCode'] = df['YearsCode'].astype(float)

In [101]:
df['YearsCode'].unique()

array([ 4., nan,  3., 16., 13.,  6.,  8., 12.,  2.,  5., 17., 10., 14.,
       35.,  7.,  0., 30.,  9., 26., 40., 19., 15., 20., 28., 25.,  1.,
       22., 11., 33., 50., 41., 18., 34., 24., 23., 42., 27., 21., 36.,
       32., 39., 38., 31., 37., 51., 29., 44., 45., 48., 46., 43., 47.,
       49.])

In [102]:
df['YearsCode'].mean()

11.662114216834588

In [103]:
df['YearsCode'].median()

9.0

### Lec 10

## Lec 11 - Read and write data from/to diff sources

In [104]:
df = pd.read_csv('results.csv', index_col='Respondent', na_values=na_vals) # na_values = nan
schema_df = pd.read_csv('schema.csv', index_col='Column')

In [106]:
# to display max no of rows and colms
pd.set_option('display.max_columns', 85)
pd.set_option('display.max_rows',85)

In [107]:
df

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;JavaScript;Other(s):,C++;HTML/CSS;JavaScript;SQL;WebAssembly;Other(s):,Firebase;SQLite,Firebase;MySQL;SQLite,Linux,Google Cloud Platform;Linux,jQuery,jQuery;Vue.js,Node.js,React Native;Unity 3D;Unreal Engine,Atom;Visual Studio;Visual Studio Code,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,What?,YouTube,NaN,Username,I don't remember,A few times per week,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","No, not at all",NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,NaN,NaN,8,11,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...,C;C++;C#;HTML/CSS;Java;Objective-C;SQL;Swift,DynamoDB;MariaDB;Microsoft SQL Server;MySQL,MariaDB;MySQL;Oracle;SQLite,iOS;Linux;MacOS;WordPress,Android;AWS;Google Cloud Platform;IBM Cloud or...,Django;jQuery;React.js,Django,Unity 3D;Unreal Engine,NaN,Android Studio;Atom;Eclipse;NetBeans;Notepad++...,Linux-based,Production,NaN,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Also Yes,Yes,WhatsApp,In real life (in person),NaN,2012,Daily or almost daily,Find answers to specific questions;Learn how t...,6-10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [109]:
filt = (df['Country'] == 'India')  
india_df = df.loc[filt]  # all respondents from india
india_df.head()

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
8,I code primarily as a hobby,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,NaN,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",NaN,"Developer, back-end;Engineer, site reliability",8,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...,Bash/Shell/PowerShell;C;C++;Elixir;Erlang;Go;P...,Cassandra;Elasticsearch;MongoDB;MySQL;Oracle;R...,Cassandra;DynamoDB;Elasticsearch;Firebase;Mong...,AWS;Docker;Heroku;Linux;MacOS;Slack,Android;Arduino;AWS;Docker;Google Cloud Platfo...,Express;Flask;React.js;Spring,Django;Express;Flask;React.js;Vue.js,Hadoop;Node.js;Pandas,Ansible;Apache Spark;Chef;Hadoop;Node.js;Panda...,Atom;IntelliJ;IPython / Jupyter;PyCharm;Visual...,Linux-based,Development;Testing;Production;Outside of work...,NaN,Useful across many domains and could change ma...,Yes,SIGH,Yes,YouTube,In real life (in person),Handle,2012,A few times per week,Find answers to specific questions;Learn how t...,Less than once per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","Yes, definitely",A lot more welcome now than last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,NaN,NaN,Appropriate in length,Neither easy nor difficult
10,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,NaN,"10,000 or more employees",Data or business analyst;Data scientist or mac...,12,20,10,Slightly dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,Yes,"I’m not actively looking, but I am open to new...",3-4 years ago,NaN,No,"Languages, frameworks, and other technologies ...",NaN,INR,Indian rupee,950000.0,Yearly,13293.0,70.0,There's no schedule or spec; I work on what se...,NaN,A few days each month,Home,Far above average,"Yes, because I see value in code review",4.0,"Yes, it's part of our process",NaN,NaN,C#;Go;JavaScript;Python;R;SQL,C#;Go;JavaScript;Kotlin;Python;R;SQL,Elasticsearch;MongoDB;Microsoft SQL Server;MyS...,Elasticsearch;MongoDB;Microsoft SQL Server,Linux;Windows,Android;Linux;Raspberry Pi;Windows,Angular/Angular.js;ASP.NET;Django;Express;Flas...,Angular/Angular.js;ASP.NET;Django;Express;Flas...,.NET;Node.js;Pandas;Torch/PyTorch,.NET;Node.js;TensorFlow;Torch/PyTorch,Android Studio;Eclipse;IPython / Jupyter;Notep...,Windows,NaN,Not at all,Useful for immutable record keeping outside of...,No,Yes,Yes,YouTube,Neither,Screen Name,NaN,Multiple times per day,Find answers to specific questions;Get a sense...,3-5 times per week,They were about the same,NaN,Yes,A few times per month or weekly,Yes,"No, and I don't know what those are","Yes, somewhat",Somewhat less welcome now than last year,Tech articles written by other developers;Tech...,NaN,NaN,NaN,NaN,NaN,Yes,Too long,Difficult
15,I am a student who is learning to code,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,Student,3,13,NaN,NaN,NaN,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",I've never had a job,NaN,NaN,"Industry that I'd be working in;Languages, fra...","Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly;Bash/Shell/PowerShell;C;C++;HTML/CSS;...,Assembly;Bash/Shell/PowerShell;C;C++;C#;Go;HTM...,MariaDB;MySQL;Oracle;SQLite,MariaDB;MongoDB;Microsoft SQL Server;MySQL;Ora...,Linux;Windows,Android;Google Cloud Platform;iOS;Linux;MacOS;...,NaN,Angular/Angular.js;ASP.NET;Django;Drupal;jQuer...,NaN,.NET;.NET Core;Node.js;TensorFlow;Unity 3D;Unr...,Atom;NetBeans;Notepad++;Sublime Text;Vim,Linux-based,Development,NaN,NaN,Yes,Yes,What?,YouTube,In real life (in person),NaN,2018,Daily or almost daily,Find answers to specific questions;Learn how t...,More than 10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,20.0,Man,No,NaN,NaN,Yes,Too long,Neither easy nor difficult
50,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of LOWER quality than prop...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",Received on-the-job training in software devel...,"10,000 or more employees","Developer, back-end;DevOps specialist",7,15,2,Slightly satisfied,Very satisfied,Very confident,Not sure,Yes,"I’m not actively looking, but I am open to new...",1-2 years ago,"Write code by hand (e.g., on a whiteboard);Int...",No,Specific department or team I'd be working on;...,I was preparing for a job search,INR,Indian rupee,400000.0,Yearly,5597.0,7.0,There is a schedule and/or spec (made by me or...,Meetings;Time spent commuting,Less than once per month / Never,"Other place, such as a coworking space or cafe",Average,No,NaN,"Yes, it's not part of our process but the deve...","The CTO, CIO, or other management purchase new...",I have little or no influence,Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...,HTML/CSS;JavaScript;Python,Elasticsearch;Firebase;MariaDB;MongoDB;MySQL;O...,Firebase;PostgreSQL;Redis;Other(s):,Arduino;AWS;Heroku;Linux;MacOS;Raspberry Pi;Wo...,AWS;Docker;Heroku;Kubernetes;Linux;MacOS;WordP...,Django;Express;Flask;jQuery,Express;Flask;jQuery;React.js;Vue.js,Node.js,Node.js,Notepad++;Visual Studio Code,MacOS,Testing,Not at all,Useful for immutable record keeping outside of...,Yes,Also Yes,What?,YouTube,In real life (in person),Username,2012,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, definitely",Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,23.0,Man,No,NaN,South Asian,No,Too long,Easy
65,I am a developer by profession,Yes,Never,NaN,Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",NaN,20 to 99 employees,"Developer, front-end;Developer, mobile",2,17,2,Very satisfied,Very satisfied,Very confident,No,Not sure,"I’m not actively looking, but I am open to new...",Less than a year ago,Write any code;Solve a brain-teaser style puzz...,No,"Languages, frameworks, and other technologies ...","My job status changed (promotion, new job, etc.)",INR,Indian rupee,NaN,Monthly,NaN,48.0,There's no schedule or spec; I work on what se...,NaN,About half the time,Office,Average,"Yes, because I see value in code review",NaN,"Yes, it's not part of our process but the deve...",Not sure,NaN,Assembly;C;C++;C#;HTML/CSS;Java,Kotlin,Firebase;MySQL;Oracle;SQLite,Firebase;SQLite,Android,Android,ASP.NET,NaN,NaN,NaN,Android Studio;IntelliJ,Linux-based,NaN,NaN,NaN,Yes,Yes,What?,WhatsApp,In real life (in person),NaN,2017,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,A few times per week,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are",Not sure,A lot more welcome now than last year,NaN,21.0,Man,No,NaN,NaN,Yes,Appropriate in length,Neither easy nor difficult

### Exprot data to CSV file

In [110]:
india_df.to_csv('modified.csv')

In [111]:
# data separate dy custom delimeter like tab, | etc

india_df.to_csv('modified.tsv', sep ='\t') # tab here

#### Writing to Excel 
##### Need to install below packages
##### pip install xlwt openpyxl xlrd
#####  xlwt - for older excel files,  openpyxl -for newer excel files,  xlrd - read and write on excel

In [113]:
# pip install xlwt openpyxl xlrd

Collecting xlwtNote: you may need to restart the kernel to use updated packages.

  Downloading xlwt-1.3.0-py2.py3-none-any.whl (99 kB)
                                              0.0/100.0 kB ? eta -:--:--
     -------------------------------------- 100.0/100.0 kB 5.6 MB/s eta 0:00:00
Requirement already satisfied: openpyxl in c:\users\susajjit\anaconda3\lib\site-packages (3.1.5)
Collecting xlrd
  Downloading xlrd-2.0.2-py2.py3-none-any.whl (96 kB)
                                              0.0/96.6 kB ? eta -:--:--
     ---------------------------------------- 96.6/96.6 kB 5.4 MB/s eta 0:00:00
Requirement already satisfied: et-xmlfile in c:\users\susajjit\anaconda3\lib\site-packages (from openpyxl) (2.0.0)
Installing collected packages: xlwt, xlrd
Successfully installed xlrd-2.0.2 xlwt-1.3.0

In [114]:
india_df.to_excel('modified.xlsx')

##### Reading from excel file

In [115]:
test = pd.read_excel('modified.xlsx', index_col = 'Respondent')

In [116]:
test.head()

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
8,I code primarily as a hobby,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,NaN,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",NaN,"Developer, back-end;Engineer, site reliability",8,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...,Bash/Shell/PowerShell;C;C++;Elixir;Erlang;Go;P...,Cassandra;Elasticsearch;MongoDB;MySQL;Oracle;R...,Cassandra;DynamoDB;Elasticsearch;Firebase;Mong...,AWS;Docker;Heroku;Linux;MacOS;Slack,Android;Arduino;AWS;Docker;Google Cloud Platfo...,Express;Flask;React.js;Spring,Django;Express;Flask;React.js;Vue.js,Hadoop;Node.js;Pandas,Ansible;Apache Spark;Chef;Hadoop;Node.js;Panda...,Atom;IntelliJ;IPython / Jupyter;PyCharm;Visual...,Linux-based,Development;Testing;Production;Outside of work...,NaN,Useful across many domains and could change ma...,Yes,SIGH,Yes,YouTube,In real life (in person),Handle,2012,A few times per week,Find answers to specific questions;Learn how t...,Less than once per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","Yes, definitely",A lot more welcome now than last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,NaN,NaN,Appropriate in length,Neither easy nor difficult
10,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,NaN,"10,000 or more employees",Data or business analyst;Data scientist or mac...,12,20,10,Slightly dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,Yes,"I’m not actively looking, but I am open to new...",3-4 years ago,NaN,No,"Languages, frameworks, and other technologies ...",NaN,INR,Indian rupee,950000.0,Yearly,13293.0,70.0,There's no schedule or spec; I work on what se...,NaN,A few days each month,Home,Far above average,"Yes, because I see value in code review",4.0,"Yes, it's part of our process",NaN,NaN,C#;Go;JavaScript;Python;R;SQL,C#;Go;JavaScript;Kotlin;Python;R;SQL,Elasticsearch;MongoDB;Microsoft SQL Server;MyS...,Elasticsearch;MongoDB;Microsoft SQL Server,Linux;Windows,Android;Linux;Raspberry Pi;Windows,Angular/Angular.js;ASP.NET;Django;Express;Flas...,Angular/Angular.js;ASP.NET;Django;Express;Flas...,.NET;Node.js;Pandas;Torch/PyTorch,.NET;Node.js;TensorFlow;Torch/PyTorch,Android Studio;Eclipse;IPython / Jupyter;Notep...,Windows,NaN,Not at all,Useful for immutable record keeping outside of...,No,Yes,Yes,YouTube,Neither,Screen Name,NaN,Multiple times per day,Find answers to specific questions;Get a sense...,3-5 times per week,They were about the same,NaN,Yes,A few times per month or weekly,Yes,"No, and I don't know what those are","Yes, somewhat",Somewhat less welcome now than last year,Tech articles written by other developers;Tech...,NaN,NaN,NaN,NaN,NaN,Yes,Too long,Difficult
15,I am a student who is learning to code,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,Student,3,13,NaN,NaN,NaN,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",I've never had a job,NaN,NaN,"Industry that I'd be working in;Languages, fra...","Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly;Bash/Shell/PowerShell;C;C++;HTML/CSS;...,Assembly;Bash/Shell/PowerShell;C;C++;C#;Go;HTM...,MariaDB;MySQL;Oracle;SQLite,MariaDB;MongoDB;Microsoft SQL Server;MySQL;Ora...,Linux;Windows,Android;Google Cloud Platform;iOS;Linux;MacOS;...,NaN,Angular/Angular.js;ASP.NET;Django;Drupal;jQuer...,NaN,.NET;.NET Core;Node.js;TensorFlow;Unity 3D;Unr...,Atom;NetBeans;Notepad++;Sublime Text;Vim,Linux-based,Development,NaN,NaN,Yes,Yes,What?,YouTube,In real life (in person),NaN,2018,Daily or almost daily,Find answers to specific questions;Learn how t...,More than 10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,20.0,Man,No,NaN,NaN,Yes,Too long,Neither easy nor difficult
50,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of LOWER quality than prop...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",Received on-the-job training in software devel...,"10,000 or more employees","Developer, back-end;DevOps specialist",7,15,2,Slightly satisfied,Very satisfied,Very confident,Not sure,Yes,"I’m not actively looking, but I am open to new...",1-2 years ago,"Write code by hand (e.g., on a whiteboard);Int...",No,Specific department or team I'd be working on;...,I was preparing for a job search,INR,Indian rupee,400000.0,Yearly,5597.0,7.0,There is a schedule and/or spec (made by me or...,Meetings;Time spent commuting,Less than once per month / Never,"Other place, such as a coworking space or cafe",Average,No,NaN,"Yes, it's not part of our process but the deve...","The CTO, CIO, or other management purchase new...",I have little or no influence,Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...,HTML/CSS;JavaScript;Python,Elasticsearch;Firebase;MariaDB;MongoDB;MySQL;O...,Firebase;PostgreSQL;Redis;Other(s):,Arduino;AWS;Heroku;Linux;MacOS;Raspberry Pi;Wo...,AWS;Docker;Heroku;Kubernetes;Linux;MacOS;WordP...,Django;Express;Flask;jQuery,Express;Flask;jQuery;React.js;Vue.js,Node.js,Node.js,Notepad++;Visual Studio Code,MacOS,Testing,Not at all,Useful for immutable record keeping outside of...,Yes,Also Yes,What?,YouTube,In real life (in person),Username,2012,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, definitely",Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,23.0,Man,No,NaN,South Asian,No,Too long,Easy
65,I am a developer by profession,Yes,Never,NaN,Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",NaN,20 to 99 employees,"Developer, front-end;Developer, mobile",2,17,2,Very satisfied,Very satisfied,Very confident,No,Not sure,"I’m not actively looking, but I am open to new...",Less than a year ago,Write any code;Solve a brain-teaser style puzz...,No,"Languages, frameworks, and other technologies ...","My job status changed (promotion, new job, etc.)",INR,Indian rupee,NaN,Monthly,NaN,48.0,There's no schedule or spec; I work on what se...,NaN,About half the time,Office,Average,"Yes, because I see value in code review",NaN,"Yes, it's not part of our process but the deve...",Not sure,NaN,Assembly;C;C++;C#;HTML/CSS;Java,Kotlin,Firebase;MySQL;Oracle;SQLite,Firebase;SQLite,Android,Android,ASP.NET,NaN,NaN,NaN,Android Studio;IntelliJ,Linux-based,NaN,NaN,NaN,Yes,Yes,What?,WhatsApp,In real life (in person),NaN,2017,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,A few times per week,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are",Not sure,A lot more welcome now than last year,NaN,21.0,Man,No,NaN,NaN,Yes,Appropriate in length,Neither easy nor difficult

###  Read and Write  on JSON

In [118]:
# india_df.to_json('modified.json')

In [120]:
# to make json list(array) like rather than dictionary ({{}}) like
# lines=True (gave error) - put each of orient = 'records' on a new  line

# india_df.to_json('modified1.json', orient = 'records', lines=False)

In [125]:
# Read from json
# test = pd.read_json('modified.json', orient = 'records', lines=False)

In [126]:
# test.head()

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
8,I code primarily as a hobby,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,None,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",None,"Developer, back-end;Engineer, site reliability",8,16,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,NaN,NaN,None,None,None,None,None,None,NaN,None,None,None,Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...,Bash/Shell/PowerShell;C;C++;Elixir;Erlang;Go;P...,Cassandra;Elasticsearch;MongoDB;MySQL;Oracle;R...,Cassandra;DynamoDB;Elasticsearch;Firebase;Mong...,AWS;Docker;Heroku;Linux;MacOS;Slack,Android;Arduino;AWS;Docker;Google Cloud Platfo...,Express;Flask;React.js;Spring,Django;Express;Flask;React.js;Vue.js,Hadoop;Node.js;Pandas,Ansible;Apache Spark;Chef;Hadoop;Node.js;Panda...,Atom;IntelliJ;IPython / Jupyter;PyCharm;Visual...,Linux-based,Development;Testing;Production;Outside of work...,None,Useful across many domains and could change ma...,Yes,SIGH,Yes,YouTube,In real life (in person),Handle,2012,A few times per week,Find answers to specific questions;Learn how t...,Less than once per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","Yes, definitely",A lot more welcome now than last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,None,None,Appropriate in length,Neither easy nor difficult
10,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",None,None,"10,000 or more employees",Data or business analyst;Data scientist or mac...,12,20,10,Slightly dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,Yes,"I’m not actively looking, but I am open to new...",3-4 years ago,None,No,"Languages, frameworks, and other technologies ...",None,INR,Indian rupee,950000.0,Yearly,13293.0,70.0,There's no schedule or spec; I work on what se...,None,A few days each month,Home,Far above average,"Yes, because I see value in code review",4.0,"Yes, it's part of our process",None,None,C#;Go;JavaScript;Python;R;SQL,C#;Go;JavaScript;Kotlin;Python;R;SQL,Elasticsearch;MongoDB;Microsoft SQL Server;MyS...,Elasticsearch;MongoDB;Microsoft SQL Server,Linux;Windows,Android;Linux;Raspberry Pi;Windows,Angular/Angular.js;ASP.NET;Django;Express;Flas...,Angular/Angular.js;ASP.NET;Django;Express;Flas...,.NET;Node.js;Pandas;Torch/PyTorch,.NET;Node.js;TensorFlow;Torch/PyTorch,Android Studio;Eclipse;IPython / Jupyter;Notep...,Windows,None,Not at all,Useful for immutable record keeping outside of...,No,Yes,Yes,YouTube,Neither,Screen Name,None,Multiple times per day,Find answers to specific questions;Get a sense...,3-5 times per week,They were about the same,None,Yes,A few times per month or weekly,Yes,"No, and I don't know what those are","Yes, somewhat",Somewhat less welcome now than last year,Tech articles written by other developers;Tech...,NaN,None,None,None,None,Yes,Too long,Difficult
15,I am a student who is learning to code,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,"Yes, full-time","Secondary school (e.g. American high school, G...",None,Taken an online course in programming or softw...,None,Student,3,13,None,None,None,None,None,None,"I’m not actively looking, but I am open to new...",I've never had a job,None,None,"Industry that I'd be working in;Languages, fra...","Something else changed (education, award, medi...",None,None,NaN,None,NaN,NaN,None,None,None,None,None,None,NaN,None,None,None,Assembly;Bash/Shell/PowerShell;C;C++;HTML/CSS;...,Assembly;Bash/Shell/PowerShell;C;C++;C#;Go;HTM...,MariaDB;MySQL;Oracle;SQLite,MariaDB;MongoDB;Microsoft SQL Server;MySQL;Ora...,Linux;Windows,Android;Google Cloud Platform;iOS;Linux;MacOS;...,None,Angular/Angular.js;ASP.NET;Django;Drupal;jQuer...,None,.NET;.NET Core;Node.js;TensorFlow;Unity 3D;Unr...,Atom;NetBeans;Notepad++;Sublime Text;Vim,Linux-based,Development,None,None,Yes,Yes,What?,YouTube,In real life (in person),None,2018,Daily or almost daily,Find answers to specific questions;Learn how t...,More than 10 times per week,They were about the same,None,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,20.0,Man,No,None,None,Yes,Too long,Neither easy nor difficult
50,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of LOWER quality than prop...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",Received on-the-job training in software devel...,"10,000 or more employees","Developer, back-end;DevOps specialist",7,15,2,Slightly satisfied,Very satisfied,Very confident,Not sure,Yes,"I’m not actively looking, but I am open to new...",1-2 years ago,"Write code by hand (e.g., on a whiteboard);Int...",No,Specific department or team I'd be working on;...,I was preparing for a job search,INR,Indian rupee,400000.0,Yearly,5597.0,7.0,There is a schedule and/or spec (made by me or...,Meetings;Time spent commuting,Less than once per month / Never,"Other place, such as a coworking space or cafe",Average,No,NaN,"Yes, it's not part of our process but the deve...","The CTO, CIO, or other management purchase new...",I have little or no influence,Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...,HTML/CSS;JavaScript;Python,Elasticsearch;Firebase;MariaDB;MongoDB;MySQL;O...,Firebase;PostgreSQL;Redis;Other(s):,Arduino;AWS;Heroku;Linux;MacOS;Raspberry Pi;Wo...,AWS;Docker;Heroku;Kubernetes;Linux;MacOS;WordP...,Django;Express;Flask;jQuery,Express;Flask;jQuery;React.js;Vue.js,Node.js,Node.js,Notepad++;Visual Studio Code,MacOS,Testing,Not at all,Useful for immutable record keeping outside of...,Yes,Also Yes,What?,YouTube,In real life (in person),Username,2012,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, definitely",Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,23.0,Man,No,None,South Asian,No,Too long,Easy
65,I am a developer by profession,Yes,Never,None,Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",None,20 to 99 employees,"Developer, front-end;Developer, mobile",2,17,2,Very satisfied,Very satisfied,Very confident,No,Not sure,"I’m not actively looking, but I am open to new...",Less than a year ago,Write any code;Solve a brain-teaser style puzz...,No,"Languages, frameworks, and other technologies ...","My job status changed (promotion, new job, etc.)",INR,Indian rupee,NaN,Monthly,NaN,48.0,There's no schedule or spec; I work on what se...,None,About half the time,Office,Average,"Yes, because I see value in code review",NaN,"Yes, it's not part of our process but the deve...",Not sure,None,Assembly;C;C++;C#;HTML/CSS;Java,Kotlin,Firebase;MySQL;Oracle;SQLite,Firebase;SQLite,Android,Android,ASP.NET,None,None,None,Android Studio;IntelliJ,Linux-based,None,None,None,Yes,Yes,What?,WhatsApp,In real life (in person),None,2017,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,A few times per week,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are",Not sure,A lot more welcome now than last year,None,21.0,Man,No,None,None,Yes,Appropriate in length,Neither easy nor difficult

### Read and Write on SQL DB

In [128]:
# Package required
# !pip install SQLAlchemy

Requirement already satisfied: SQLAlchemy in c:\users\susajjit\anaconda3\lib\site-packages (2.0.48)
Requirement already satisfied: greenlet>=1 in c:\users\susajjit\anaconda3\lib\site-packages (from SQLAlchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\susajjit\anaconda3\lib\site-packages (from SQLAlchemy) (4.15.0)

In [131]:
# for working with postgres
# !pip install psycopg2-binary

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp311-cp311-win_amd64.whl (2.8 MB)
                                              0.0/2.8 MB ? eta -:--:--
     ------                                   0.4/2.8 MB 13.2 MB/s eta 0:00:01
     ----------------------                   1.5/2.8 MB 19.6 MB/s eta 0:00:01
     ---------------------------------------  2.8/2.8 MB 24.9 MB/s eta 0:00:01
     ---------------------------------------- 2.8/2.8 MB 22.0 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12

In [132]:
# from sqlalchemy import create_engine # for connecting to db
# import psycopg2

In [139]:
# %pip install pyodbc

Requirement already satisfied: pyodbc in c:\users\susajjit\anaconda3\lib\site-packages (5.3.0)Note: you may need to restart the kernel to use updated packages.

In [142]:
# import urllib
# import pandas as pd
# from sqlalchemy import create_engine

# # 1. Your connection parameters
# DB_SERVER = r"SS\SQLEXPRESS"
# DB_NAME = "Pandas_test"
# DB_USER = ""
# DB_PASSWORD = ""

# # 2. Re-create the connection string using ODBC Driver 17
# if DB_USER and DB_PASSWORD:
#     odbc_str = (
#         f"DRIVER={{ODBC Driver 17 for SQL Server}};"
#         f"SERVER={DB_SERVER};DATABASE={DB_NAME};"
#         f"UID={DB_USER};PWD={DB_PASSWORD}"
#     )
# else:
#     odbc_str = (
#         f"DRIVER={{ODBC Driver 17 for SQL Server}};"
#         f"SERVER={DB_SERVER};DATABASE={DB_NAME};"
#         f"Trusted_Connection=yes;"
#     )

# params = urllib.parse.quote_plus(odbc_str)
# connection_string = f"mssql+pyodbc:///?odbc_connect={params}"
# engine = create_engine(connection_string) # db connection

🎉 Success! The table 'scraped_companies' has been created and populated.

In [145]:
# exporting/writing to db

# india_df.to_sql('Sample_table', engine)

#### read from db

In [151]:
# # read from db
# from sqlalchemy import text

# # 1. Wrap the table query using text()
# # (Using a standard SELECT statement lets us fetch the table safely)
# query = text("SELECT * FROM Sample_table")

# # 2. Use the modern context manager to read it out safely
# with engine.connect() as conn:
#     sql_df = pd.read_sql(query, con=conn, index_col="Respondent")

# # View your newly loaded DataFrame with its custom index
# sql_df.head()

                                        MainBranch Hobbyist  \
Respondent
8                      I code primarily as a hobby      Yes
10                  I am a developer by profession      Yes
15          I am a student who is learning to code      Yes
50                  I am a developer by profession      Yes
65                  I am a developer by profession      Yes

                           OpenSourcer  \
Respondent
8              Less than once per year
10          Once a month or more often
15                               Never
50          Once a month or more often
65                               Never

                                                   OpenSource  \
Respondent
8           OSS is, on average, of HIGHER quality than pro...
10          OSS is, on average, of HIGHER quality than pro...
15          OSS is, on average, of HIGHER quality than pro...
50          OSS is, on average, of LOWER quality than prop...
65                                                       None

                                    Employment Country         Student  \
Respondent
8           Not employed, but looking for work   India            None
10                          Employed full-time   India              No
15          Not employed, but looking for work   India  Yes, full-time
50                          Employed full-time   India              No
65                          Employed full-time   India              No

                                                      EdLevel  \
Respondent
8                    Bachelor’s degree (BA, BS, B.Eng., etc.)
10                Master’s degree (MA, MS, M.Eng., MBA, etc.)
15          Secondary school (e.g. American high school, G...
50                   Bachelor’s degree (BA, BS, B.Eng., etc.)
65                   Bachelor’s degree (BA, BS, B.Eng., etc.)

                                               UndergradMajor  \
Respondent
8           Computer science, computer engineering, or sof...
10                                                       None
15                                                       None
50          Another engineering discipline (ex. civil, ele...
65          Information systems, information technology, o...

                                                     EduOther  \
Respondent
8           Taught yourself a new language, framework, or ...
10                                                       None
15          Taken an online course in programming or softw...
50          Received on-the-job training in software devel...
65                                                       None

                             OrgSize  \
Respondent
8                               None
10          10,000 or more employees
15                              None
50          10,000 or more employees
65                20 to 99 employees

                                                      DevType YearsCode  \
Respondent
8              Developer, back-end;Engineer, site reliability         8
10          Data or business analyst;Data scientist or mac...        12
15                                                    Student         3
50                      Developer, back-end;DevOps specialist         7
65                     Developer, front-end;Developer, mobile         2

           Age1stCode YearsCodePro              CareerSat  \
Respondent
8                  16         None                   None
10                 20           10  Slightly dissatisfied
15                 13         None                   None
50                 15            2     Slightly satisfied
65                 17            2         Very satisfied

                           JobSat            MgrIdiot  MgrMoney   MgrWant  \
Respondent
8                            None                None      None      None
10          Slightly dissatisfied  Somewhat confident       Yes       Yes
15                           None                None      None      None
50                 Very satisfied      Very confident  Not sure       Yes
65                 Very satisfied      Very confident        No  Not sure

                                                      JobSeek  \
Respondent
8                                                        None
10          I’m not actively looking, but I am open to new...
15          I’m not actively looking, but I am open to new...
50          I’m not actively looking, but I am open to new...
65          I’m not actively looking, but I am open to new...

                    LastHireDate  \
Respondent
8                           None
10                 3-4 years ago
15          I've never had a job
50                 1-2 years ago
65          Less than a year ago

                                                      LastInt FizzBuzz  \
Respondent
8                                                        None     None
10                                                       None       No
15                                                       None     None
50          Write code by hand (e.g., on a whiteboard);Int...       No
65          Write any code;Solve a brain-teaser style puzz...       No

                                                   JobFactors  \
Respondent
8                                                        None
10          Languages, frameworks, and other technologies ...
15          Industry that I'd be working in;Languages, fra...
50          Specific department or team I'd be working on;...
65          Languages, frameworks, and other technologies ...

                                                 ResumeUpdate CurrencySymbol  \
Respondent
8                                                        None           None
10                                                       None            INR
15          Something else changed (education, award, medi...           None
50                           I was preparing for a job search            INR
65           My job status changed (promotion, new job, etc.)            INR

            CurrencyDesc  CompTotal CompFreq  ConvertedComp  WorkWeekHrs  \
Respondent
8                   None        NaN     None            NaN          NaN
10          Indian rupee   950000.0   Yearly        13293.0         70.0
15                  None        NaN     None            NaN          NaN
50          Indian rupee   400000.0   Yearly         5597.0          7.0
65          Indian rupee        NaN  Monthly            NaN         48.0

                                                     WorkPlan  \
Respondent
8                                                        None
10          There's no schedule or spec; I work on what se...
15                                                       None
50          There is a schedule and/or spec (made by me or...
65          There's no schedule or spec; I work on what se...

                            WorkChallenge                        WorkRemote  \
Respondent
8                                    None                              None
10                                   None             A few days each month
15                                   None                              None
50          Meetings;Time spent commuting  Less than once per month / Never
65                                   None               About half the time

                                                   WorkLoc             ImpSyn  \
Respondent
8                                                     None               None
10                                                    Home  Far above average
15                                                    None               None
50          Other place, such as a coworking space or cafe            Average
65                                                  Office            Average

                                            CodeRev  CodeRevHrs  \
Respondent
8                                              None         NaN
10          Yes, because I see value in code review         4.0
15                                             None         NaN
50                                               No         NaN
65          Yes, because I see value in code review         NaN

                                                    UnitTests  \
Respondent
8                                                        None
10                              Yes, it's part of our process
15                                                       None
50          Yes, it's not part of our process but the deve...
65          Yes, it's not part of our process but the deve...

                                                  PurchaseHow  \
Respondent
8                                                        None
10                                                       None
15                                                       None
50          The CTO, CIO, or other management purchase new...
65                                                   Not sure

                             PurchaseWhat  \
Respondent
8                                    None
10                                   None
15                                   None
50          I have little or no influence
65                                   None

                                           LanguageWorkedWith  \
Respondent
8           Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...
10                              C#;Go;JavaScript;Python;R;SQL
15          Assembly;Bash/Shell/PowerShell;C;C++;HTML/CSS;...
50          Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...
65                            Assembly;C;C++;C#;HTML/CSS;Java

                                       LanguageDesireNextYear  \
Respondent
8           Bash/Shell/PowerShell;C;C++;Elixir;Erlang;Go;P...
10                       C#;Go;JavaScript;Kotlin;Python;R;SQL
15          Assembly;Bash/Shell/PowerShell;C;C++;C#;Go;HTM...
50                                 HTML/CSS;JavaScript;Python
65                                                     Kotlin

                                           DatabaseWorkedWith  \
Respondent
8           Cassandra;Elasticsearch;MongoDB;MySQL;Oracle;R...
10          Elasticsearch;MongoDB;Microsoft SQL Server;MyS...
15                                MariaDB;MySQL;Oracle;SQLite
50          Elasticsearch;Firebase;MariaDB;MongoDB;MySQL;O...
65                               Firebase;MySQL;Oracle;SQLite

                                       DatabaseDesireNextYear  \
Respondent
8           Cassandra;DynamoDB;Elasticsearch;Firebase;Mong...
10                 Elasticsearch;MongoDB;Microsoft SQL Server
15          MariaDB;MongoDB;Microsoft SQL Server;MySQL;Ora...
50                        Firebase;PostgreSQL;Redis;Other(s):
65                                            Firebase;SQLite

                                           PlatformWorkedWith  \
Respondent
8                         AWS;Docker;Heroku;Linux;MacOS;Slack
10                                              Linux;Windows
15                                              Linux;Windows
50          Arduino;AWS;Heroku;Linux;MacOS;Raspberry Pi;Wo...
65                                                    Android

                                       PlatformDesireNextYear  \
Respondent
8           Android;Arduino;AWS;Docker;Google Cloud Platfo...
10                         Android;Linux;Raspberry Pi;Windows
15          Android;Google Cloud Platform;iOS;Linux;MacOS;...
50          AWS;Docker;Heroku;Kubernetes;Linux;MacOS;WordP...
65                                                    Android

                                           WebFrameWorkedWith  \
Respondent
8                               Express;Flask;React.js;Spring
10          Angular/Angular.js;ASP.NET;Django;Express;Flas...
15                                                       None
50                                Django;Express;Flask;jQuery
65                                                    ASP.NET

                                       WebFrameDesireNextYear  \
Respondent
8                        Django;Express;Flask;React.js;Vue.js
10          Angular/Angular.js;ASP.NET;Django;Express;Flas...
15          Angular/Angular.js;ASP.NET;Django;Drupal;jQuer...
50                       Express;Flask;jQuery;React.js;Vue.js
65                                                       None

                           MiscTechWorkedWith  \
Respondent
8                       Hadoop;Node.js;Pandas
10          .NET;Node.js;Pandas;Torch/PyTorch
15                                       None
50                                    Node.js
65                                       None

                                       MiscTechDesireNextYear  \
Respondent
8           Ansible;Apache Spark;Chef;Hadoop;Node.js;Panda...
10                      .NET;Node.js;TensorFlow;Torch/PyTorch
15          .NET;.NET Core;Node.js;TensorFlow;Unity 3D;Unr...
50                                                    Node.js
65                                                       None

                                                   DevEnviron        OpSys  \
Respondent
8           Atom;IntelliJ;IPython / Jupyter;PyCharm;Visual...  Linux-based
10          Android Studio;Eclipse;IPython / Jupyter;Notep...      Windows
15                   Atom;NetBeans;Notepad++;Sublime Text;Vim  Linux-based
50                               Notepad++;Visual Studio Code        MacOS
65                                    Android Studio;IntelliJ  Linux-based

                                                   Containers BlockchainOrg  \
Respondent
8           Development;Testing;Production;Outside of work...          None
10                                                       None    Not at all
15                                                Development          None
50                                                    Testing    Not at all
65                                                       None          None

                                                 BlockchainIs BetterLife  \
Respondent
8           Useful across many domains and could change ma...        Yes
10          Useful for immutable record keeping outside of...         No
15                                                       None        Yes
50          Useful for immutable record keeping outside of...        Yes
65                                                       None        Yes

            ITperson  OffOn SocialMedia              Extraversion  \
Respondent
8               SIGH    Yes     YouTube  In real life (in person)
10               Yes    Yes     YouTube                   Neither
15               Yes  What?     YouTube  In real life (in person)
50          Also Yes  What?     YouTube  In real life (in person)
65               Yes  What?    WhatsApp  In real life (in person)

             ScreenName SOVisit1st             SOVisitFreq  \
Respondent
8                Handle       2012    A few times per week
10          Screen Name       None  Multiple times per day
15                 None       2018   Daily or almost daily
50             Username       2012   Daily or almost daily
65                 None       2017  Multiple times per day

                                                    SOVisitTo  \
Respondent
8           Find answers to specific questions;Learn how t...
10          Find answers to specific questions;Get a sense...
15          Find answers to specific questions;Learn how t...
50          Find answers to specific questions;Learn how t...
65                         Find answers to specific questions

                           SOFindAnswer                         SOTimeSaved  \
Respondent
8               Less than once per week  Stack Overflow was slightly faster
10                   3-5 times per week            They were about the same
15          More than 10 times per week            They were about the same
50                   3-5 times per week  Stack Overflow was slightly faster
65          More than 10 times per week  Stack Overflow was slightly faster

            SOHowMuchTime SOAccount                           SOPartFreq  \
Respondent
8           11-30 minutes       Yes  Less than once per month or monthly
10                   None       Yes      A few times per month or weekly
15                   None       Yes  Less than once per month or monthly
50          11-30 minutes       Yes  Less than once per month or monthly
65          11-30 minutes       Yes                 A few times per week

                                                       SOJobs  \
Respondent
8                                                         Yes
10                                                        Yes
15                                                        Yes
50          No, I knew that Stack Overflow had a job board...
65          No, I knew that Stack Overflow had a job board...

                                                     EntTeams  \
Respondent
8                         No, and I don't know what those are
10                        No, and I don't know what those are
15          No, I've heard of them, but I am not part of a...
50                        No, and I don't know what those are
65                        No, and I don't know what those are

                     SOComm                             WelcomeChange  \
Respondent
8           Yes, definitely     A lot more welcome now than last year
10            Yes, somewhat  Somewhat less welcome now than last year
15            Yes, somewhat   Just as welcome now as I felt last year
50          Yes, definitely   Just as welcome now as I felt last year
65                 Not sure     A lot more welcome now than last year

                                                 SONewContent   Age Gender  \
Respondent
8           Tech articles written by other developers;Indu...  24.0    Man
10          Tech articles written by other developers;Tech...   NaN   None
15          Tech articles written by other developers;Indu...  20.0    Man
50          Tech articles written by other developers;Tech...  23.0    Man
65                                                       None  21.0    Man

           Trans                Sexuality    Ethnicity Dependents  \
Respondent
8             No  Straight / Heterosexual         None       None
10          None                     None         None        Yes
15            No                     None         None        Yes
50            No                     None  South Asian         No
65            No                     None         None        Yes

                     SurveyLength                  SurveyEase
Respondent
8           Appropriate in length  Neither easy nor difficult
10                       Too long                   Difficult
15                       Too long  Neither easy nor difficult
50                       Too long                        Easy
65          Appropriate in length  Neither easy nor difficult

In [152]:
sql_df.head()

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
8,I code primarily as a hobby,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,None,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",None,"Developer, back-end;Engineer, site reliability",8,16,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,NaN,NaN,None,None,None,None,None,None,NaN,None,None,None,Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...,Bash/Shell/PowerShell;C;C++;Elixir;Erlang;Go;P...,Cassandra;Elasticsearch;MongoDB;MySQL;Oracle;R...,Cassandra;DynamoDB;Elasticsearch;Firebase;Mong...,AWS;Docker;Heroku;Linux;MacOS;Slack,Android;Arduino;AWS;Docker;Google Cloud Platfo...,Express;Flask;React.js;Spring,Django;Express;Flask;React.js;Vue.js,Hadoop;Node.js;Pandas,Ansible;Apache Spark;Chef;Hadoop;Node.js;Panda...,Atom;IntelliJ;IPython / Jupyter;PyCharm;Visual...,Linux-based,Development;Testing;Production;Outside of work...,None,Useful across many domains and could change ma...,Yes,SIGH,Yes,YouTube,In real life (in person),Handle,2012,A few times per week,Find answers to specific questions;Learn how t...,Less than once per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","Yes, definitely",A lot more welcome now than last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,None,None,Appropriate in length,Neither easy nor difficult
10,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",None,None,"10,000 or more employees",Data or business analyst;Data scientist or mac...,12,20,10,Slightly dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,Yes,"I’m not actively looking, but I am open to new...",3-4 years ago,None,No,"Languages, frameworks, and other technologies ...",None,INR,Indian rupee,950000.0,Yearly,13293.0,70.0,There's no schedule or spec; I work on what se...,None,A few days each month,Home,Far above average,"Yes, because I see value in code review",4.0,"Yes, it's part of our process",None,None,C#;Go;JavaScript;Python;R;SQL,C#;Go;JavaScript;Kotlin;Python;R;SQL,Elasticsearch;MongoDB;Microsoft SQL Server;MyS...,Elasticsearch;MongoDB;Microsoft SQL Server,Linux;Windows,Android;Linux;Raspberry Pi;Windows,Angular/Angular.js;ASP.NET;Django;Express;Flas...,Angular/Angular.js;ASP.NET;Django;Express;Flas...,.NET;Node.js;Pandas;Torch/PyTorch,.NET;Node.js;TensorFlow;Torch/PyTorch,Android Studio;Eclipse;IPython / Jupyter;Notep...,Windows,None,Not at all,Useful for immutable record keeping outside of...,No,Yes,Yes,YouTube,Neither,Screen Name,None,Multiple times per day,Find answers to specific questions;Get a sense...,3-5 times per week,They were about the same,None,Yes,A few times per month or weekly,Yes,"No, and I don't know what those are","Yes, somewhat",Somewhat less welcome now than last year,Tech articles written by other developers;Tech...,NaN,None,None,None,None,Yes,Too long,Difficult
15,I am a student who is learning to code,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,"Yes, full-time","Secondary school (e.g. American high school, G...",None,Taken an online course in programming or softw...,None,Student,3,13,None,None,None,None,None,None,"I’m not actively looking, but I am open to new...",I've never had a job,None,None,"Industry that I'd be working in;Languages, fra...","Something else changed (education, award, medi...",None,None,NaN,None,NaN,NaN,None,None,None,None,None,None,NaN,None,None,None,Assembly;Bash/Shell/PowerShell;C;C++;HTML/CSS;...,Assembly;Bash/Shell/PowerShell;C;C++;C#;Go;HTM...,MariaDB;MySQL;Oracle;SQLite,MariaDB;MongoDB;Microsoft SQL Server;MySQL;Ora...,Linux;Windows,Android;Google Cloud Platform;iOS;Linux;MacOS;...,None,Angular/Angular.js;ASP.NET;Django;Drupal;jQuer...,None,.NET;.NET Core;Node.js;TensorFlow;Unity 3D;Unr...,Atom;NetBeans;Notepad++;Sublime Text;Vim,Linux-based,Development,None,None,Yes,Yes,What?,YouTube,In real life (in person),None,2018,Daily or almost daily,Find answers to specific questions;Learn how t...,More than 10 times per week,They were about the same,None,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,20.0,Man,No,None,None,Yes,Too long,Neither easy nor difficult
50,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of LOWER quality than prop...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",Received on-the-job training in software devel...,"10,000 or more employees","Developer, back-end;DevOps specialist",7,15,2,Slightly satisfied,Very satisfied,Very confident,Not sure,Yes,"I’m not actively looking, but I am open to new...",1-2 years ago,"Write code by hand (e.g., on a whiteboard);Int...",No,Specific department or team I'd be working on;...,I was preparing for a job search,INR,Indian rupee,400000.0,Yearly,5597.0,7.0,There is a schedule and/or spec (made by me or...,Meetings;Time spent commuting,Less than once per month / Never,"Other place, such as a coworking space or cafe",Average,No,NaN,"Yes, it's not part of our process but the deve...","The CTO, CIO, or other management purchase new...",I have little or no influence,Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...,HTML/CSS;JavaScript;Python,Elasticsearch;Firebase;MariaDB;MongoDB;MySQL;O...,Firebase;PostgreSQL;Redis;Other(s):,Arduino;AWS;Heroku;Linux;MacOS;Raspberry Pi;Wo...,AWS;Docker;Heroku;Kubernetes;Linux;MacOS;WordP...,Django;Express;Flask;jQuery,Express;Flask;jQuery;React.js;Vue.js,Node.js,Node.js,Notepad++;Visual Studio Code,MacOS,Testing,Not at all,Useful for immutable record keeping outside of...,Yes,Also Yes,What?,YouTube,In real life (in person),Username,2012,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, definitely",Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,23.0,Man,No,None,South Asian,No,Too long,Easy
65,I am a developer by profession,Yes,Never,None,Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",None,20 to 99 employees,"Developer, front-end;Developer, mobile",2,17,2,Very satisfied,Very satisfied,Very confident,No,Not sure,"I’m not actively looking, but I am open to new...",Less than a year ago,Write any code;Solve a brain-teaser style puzz...,No,"Languages, frameworks, and other technologies ...","My job status changed (promotion, new job, etc.)",INR,Indian rupee,NaN,Monthly,NaN,48.0,There's no schedule or spec; I work on what se...,None,About half the time,Office,Average,"Yes, because I see value in code review",NaN,"Yes, it's not part of our process but the deve...",Not sure,None,Assembly;C;C++;C#;HTML/CSS;Java,Kotlin,Firebase;MySQL;Oracle;SQLite,Firebase;SQLite,Android,Android,ASP.NET,None,None,None,Android Studio;IntelliJ,Linux-based,None,None,None,Yes,Yes,What?,WhatsApp,In real life (in person),None,2017,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,A few times per week,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are",Not sure,A lot more welcome now than last year,None,21.0,Man,No,None,None,Yes,Appropriate in length,Neither easy nor difficult

#### running read query on db

In [157]:
# 1. Explicitly wrap your query string in text()
query = text("SELECT * FROM Sample_table")

# 2. Pass the executable text object into read_sql_query
with engine.connect() as conn:
    sql_df = pd.read_sql_query(query, con=conn, index_col="Respondent")

# View your data
sql_df.head()

# or using below code

# No raw SQL or text() wrappers required for this one
with engine.connect() as conn:
    sql_df = pd.read_sql_table(
        "Sample_table", con=conn, index_col="Respondent"
    )

### Reading data from URL

In [160]:
# Use the direct raw text URL instead of the user interface page link
url = "https://raw.githubusercontent.com/CoreyMSchafer/code_snippets/master/Python/Flask_Blog/snippets/posts.json"


# json as file we are trying to read is JSON
posts_df = pd.read_json(url)

# View the downloaded data
posts_df.head()

,title,content,user_id
0,My Updated Post,My first updated post!\r\n\r\nThis is exciting!,1
1,A Second Post,This is a post from a different user...,2
2,Top 5 Programming Lanaguages,"Te melius apeirian postulant cum, labitur admo...",1
3,Sublime Text Tips and Tricks,"Ea vix dico modus voluptatibus, mel iudico sua...",1
4,Best Python IDEs,"Elit contentiones nam no, sea ut consul adipis...",1

NameError: name 'posts_df' is not defined